# Generated by Django 5.1.2 on 2024-10-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('id_venta', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('id_cliente', models.CharField(max_length=8)),
                ('id_empleado', models.CharField(max_length=12)),
            ],
        ),
    ]
